services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=vibemoment-postgres;Port=5432;Database=vibemomentdb;Username=postgres;Password=Mambastik135
    networks:
      - vibemoment-network 

networks:
  vibemoment-network:
    external: true